# Generated by Django 5.2.3 on 2025-07-01 01:44

from django.db import migrations


def create_profiles_for_existing_users(apps, schema_editor):
    """既存のユーザーにプロフィールを作成"""
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('backend', 'Profile')
    
    for user in User.objects.all():
        Profile.objects.get_or_create(
            user=user,
            defaults={'name': user.username}
        )


def reverse_create_profiles(apps, schema_editor):
    """ロールバック用（プロフィールを削除）"""
    Profile = apps.get_model('backend', 'Profile')
    Profile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_bookmark'),
    ]

    operations = [
        migrations.RunPython(create_profiles_for_existing_users, reverse_create_profiles),
    ]
